<?php
require_once($template_dir."/external/config/recaptcha.php");
require_once($template_dir."/external/lib/recaptchalib.php");
?>
<script type="text/javascript">
    var RecaptchaOptions = {
        theme : 'clean',
    };
</script>
<?php
echo recaptcha_get_html($recaptcha['publickey'], $error);
?>
<script type="text/javascript">
    (function(){
        // Hide the extra iframe that is generated by ReCAPTCHA.
        jQuery('iframe[src=about\\:blank]').hide();
    })();
</script>
